package com.dbost.app;
import android.app.*; import android.content.*; import android.graphics.*; import android.os.*; import android.view.*; import android.widget.*; import androidx.core.app.NotificationCompat; import java.io.*; import java.util.*;
public class OverlayService extends Service {
private WindowManager wm; private LinearLayout overlay; private View circle; private TextView stats, credit, ts, ss, bs, sps, rs; private Handler h; private long[] prev; private int fps, fpsCount; private long last; private Choreographer.FrameCallback cb; static final String CID="dbost";
private int ow=520; private WindowManager.LayoutParams op, cp;
private boolean tuning, spob, bypass, speed, radar, hidden;
private MemoryBridge mem=new MemoryBridge(); private int pid=-1;
private static final long OS=0x7F8A4C00L, OR=0x7F8A4C04L, OA=0x7F8A4C08L, OM=0x7F8A4C0CL, OSprint=0x7F8A4C10L, OJ=0x7F8A4C14L, OSpob=0x7F8A4C18L, OPx=0x7F8A4C20L, OPz=0x7F8A4C28L, OE=0x7F8A4C30L; private static final int ES=0x20;
@Override public void onCreate(){ super.onCreate(); createChannel(); startForeground(1,new NotificationCompat.Builder(this,CID).setContentTitle("dBost").setSmallIcon(android.R.drawable.ic_dialog_info).build()); wm=(WindowManager)getSystemService(WINDOW_SERVICE); try{System.loadLibrary("mem_bridge");}catch(Exception e){} buildOverlay(); buildCircle(); startFps(); findPid(); h=new Handler(); h.postDelayed(statsUp,1000); h.postDelayed(radarUp,200);}
private void findPid(){ try{Process p=Runtime.getRuntime().exec("ps -A"); BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream())); String l; while((l=r.readLine())!=null){ if(l.contains("com.dts.freefireth")){ pid=Integer.parseInt(l.trim().split("\\s+")[1]); mem.attach(pid); update("PID:"+pid); return;}}}catch(Exception e){update("Game not found");}}
private void buildOverlay(){ overlay=new LinearLayout(this); overlay.setOrientation(LinearLayout.VERTICAL); overlay.setBackgroundColor(Color.argb(240,8,8,14)); overlay.setPadding(14,10,14,10);
LinearLayout head=new LinearLayout(this); head.setOrientation(LinearLayout.HORIZONTAL); head.setGravity(Gravity.CENTER_VERTICAL);
TextView title=new TextView(this); title.setText("dBost"); title.setTextColor(Color.argb(255,255,200,0)); title.setTextSize(14); title.setTypeface(Typeface.DEFAULT_BOLD);
TextView dot=new TextView(this); dot.setText(" ●"); dot.setTextColor(Color.argb(255,0,255,136)); dot.setTextSize(10);
View sp=new View(this); LinearLayout.LayoutParams spp=new LinearLayout.LayoutParams(0,1,1f); sp.setLayoutParams(spp);
TextView hide=new TextView(this); hide.setText("◉"); hide.setTextColor(Color.argb(200,255,255,255)); hide.setTextSize(18); hide.setPadding(8,0,0,0); hide.setOnClickListener(v->toggleHide());
TextView resize=new TextView(this); resize.setText("⤡"); resize.setTextColor(Color.argb(120,255,255,255)); resize.setTextSize(16); resize.setPadding(8,0,0,0);
head.addView(title); head.addView(dot); head.addView(sp); head.addView(hide); head.addView(resize);
View div=new View(this); div.setBackgroundColor(Color.argb(60,255,255,255)); LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1); dp.topMargin=6; dp.bottomMargin=6;
stats=new TextView(this); stats.setText("CPU 0% | RAM 0% | FPS 0 | BAT 0%"); stats.setTextColor(Color.argb(230,220,220,235)); stats.setTextSize(10); stats.setTypeface(Typeface.MONOSPACE);
ts=new TextView(this); ss=new TextView(this); bs=new TextView(this); sps=new TextView(this); rs=new TextView(this);
overlay.addView(head); overlay.addView(div,dp); overlay.addView(stats); overlay.addView(row("TUNING:",ts,v->toggleTuning())); overlay.addView(row("SPOB:",ss,v->toggleSpob())); overlay.addView(row("BYPASS:",bs,v->toggleBypass())); overlay.addView(row("SPEED:",sps,v->toggleSpeed())); overlay.addView(row("RADAR:",rs,v->toggleRadar()));
radarView(); credit();
op=new WindowManager.LayoutParams(ow,WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL|WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,PixelFormat.TRANSLUCENT); op.gravity=Gravity.TOP|Gravity.END; op.x=12; op.y=100; overlay.setOnTouchListener(new Drag(wm,op,overlay)); resize.setOnTouchListener(new Resize()); wm.addView(overlay,op);}
private LinearLayout row(String label, TextView status, View.OnClickListener l){ LinearLayout r=new LinearLayout(this); r.setOrientation(LinearLayout.HORIZONTAL); r.setGravity(Gravity.CENTER_VERTICAL); r.setPadding(0,3,0,3); TextView lbl=new TextView(this); lbl.setText(label); lbl.setTextColor(Color.argb(180,200,200,200)); lbl.setTextSize(10); lbl.setTypeface(Typeface.MONOSPACE); lbl.setPadding(0,0,8,0); status.setText("OFF"); status.setTextColor(Color.argb(255,255,80,80)); status.setTextSize(10); status.setTypeface(Typeface.MONOSPACE); status.setPadding(0,0,12,0); Button btn=new Button(this); btn.setText("TOGGLE"); btn.setTextSize(9); btn.setBackgroundColor(Color.argb(200,40,40,60)); btn.setTextColor(Color.WHITE); btn.setPadding(10,3,10,3); btn.setOnClickListener(l); r.addView(lbl); r.addView(status); r.addView(btn); return r;}
private void radarView(){ View rv=new View(this){ @Override protected void onDraw(Canvas c){ super.onDraw(c); if(!radar||pid==-1)return; int w=getWidth(), h=getHeight(), cx=w/2, cy=h/2, rad=Math.min(w,h)/2-6; Paint p=new Paint(); p.setColor(Color.argb(120,50,50,70)); p.setStyle(Paint.Style.FILL); c.drawCircle(cx,cy,rad,p); p.setColor(Color.argb(180,100,200,255)); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(1.5f); c.drawCircle(cx,cy,rad,p); float px=mem.readFloat(OPx), pz=mem.readFloat(OPz); p.setColor(Color.argb(255,0,255,0)); p.setStyle(Paint.Style.FILL); c.drawCircle(cx,cy,4,p); float sc=rad/200f; for(int i=0;i<10;i++){ long addr=OE+(i*ES); float ex=mem.readFloat(addr), ez=mem.readFloat(addr+8); int team=mem.readInt(addr+16); if(ex==0&&ez==0)continue; float dx=ex-px, dz=ez-pz, dist=(float)Math.sqrt(dx*dx+dz*dz); if(dist>200f||dist<0.5f)continue; float ang=(float)Math.atan2(dz,dx); float rx=cx+dist*sc*(float)Math.cos(ang), ry=cy+dist*sc*(float)Math.sin(ang); int col=(team==2)?Color.argb(255,255,50,50):(team==3)?Color.argb(255,255,150,0):Color.argb(255,255,200,50); p.setColor(col); p.setStyle(Paint.Style.FILL); float ds=Math.max(3,6-dist/50f); c.drawCircle(rx,ry,ds,p);}}}; rv.setLayoutParams(new LinearLayout.LayoutParams(140,140)); rv.setBackgroundColor(Color.argb(60,0,0,0)); rv.setPadding(4,4,4,4); overlay.addView(rv);}
private void credit(){ credit=new TextView(this); credit.setText("devnsepele | non-root | hide"); credit.setTextColor(Color.argb(90,150,150,180)); credit.setTextSize(8); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,LinearLayout.LayoutParams.WRAP_CONTENT); cp.topMargin=4; credit.setLayoutParams(cp); overlay.addView(credit);}
private void buildCircle(){ circle=new View(this){ @Override protected void onDraw(Canvas c){ super.onDraw(c); int cx=getWidth()/2, cy=getHeight()/2, rad=Math.min(cx,cy)-4; Paint p=new Paint(); p.setColor(Color.argb(220,8,8,14)); p.setStyle(Paint.Style.FILL); c.drawCircle(cx,cy,rad,p); p.setColor(Color.argb(200,255,200,0)); p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(2f); c.drawCircle(cx,cy,rad,p); p.setColor(Color.argb(255,255,200,0)); p.setStyle(Paint.Style.FILL); p.setTextSize(20); p.setTypeface(Typeface.DEFAULT_BOLD); p.setTextAlign(Paint.Align.CENTER); Paint.FontMetrics fm=p.getFontMetrics(); c.drawText("dB",cx,cy-(fm.ascent+fm.descent)/2,p); int col=(tuning||spob||speed)?Color.argb(255,0,255,0):Color.argb(255,100,100,100); p.setColor(col); p.setStyle(Paint.Style.FILL); c.drawCircle(cx+rad-10,cy-rad+10,6,p);}}; circle.setLayoutParams(new ViewGroup.LayoutParams(48,48)); circle.setOnClickListener(v->toggleHide()); cp=new WindowManager.LayoutParams(48,48,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL,PixelFormat.TRANSLUCENT); cp.gravity=Gravity.TOP|Gravity.END; cp.x=20; cp.y=120; circle.setOnTouchListener(new Drag(wm,cp,circle)); circle.setVisibility(View.GONE);}
private void toggleHide(){ hidden=!hidden; if(hidden){ overlay.setVisibility(View.GONE); circle.setVisibility(View.VISIBLE); if(circle.getParent()==null)wm.addView(circle,cp);}else{ overlay.setVisibility(View.VISIBLE); circle.setVisibility(View.GONE); if(circle.getParent()!=null)wm.removeView(circle);}}
private void toggleTuning(){ tuning=!tuning; if(tuning&&pid!=-1){ mem.writeFloat(OS,95f); mem.writeFloat(OR,0f); mem.writeFloat(OA,1f); ts.setText("ON"); ts.setTextColor(Color.argb(255,0,255,136)); update("TUNING ON");}else{ if(pid!=-1){ mem.writeFloat(OS,50f); mem.writeFloat(OR,0.8f); mem.writeFloat(OA,0f);} ts.setText("OFF"); ts.setTextColor(Color.argb(255,255,80,80)); update("TUNING OFF");} circle.invalidate();}
private void toggleSpob(){ spob=!spob; if(spob&&pid!=-1){ mem.writeInt(OSpob,1); ss.setText("ON"); ss.setTextColor(Color.argb(255,0,255,136)); update("SPOB ON"); h.postDelayed(()->{ if(spob){ spob=false; mem.writeInt(OSpob,0); ss.setText("OFF"); ss.setTextColor(Color.argb(255,255,80,80)); update("SPOB OFF"); circle.invalidate();}},45000);}else{ if(pid!=-1)mem.writeInt(OSpob,0); ss.setText("OFF"); ss.setTextColor(Color.argb(255,255,80,80)); update("SPOB OFF");} circle.invalidate();}
private void toggleBypass(){ bypass=!bypass; if(bypass&&pid!=-1){ mem.writeInt(OSpob+0x100,0xDEADBEEF); bs.setText("ON"); bs.setTextColor(Color.argb(255,0,255,136)); update("BYPASS ON");}else{ bs.setText("OFF"); bs.setTextColor(Color.argb(255,255,80,80)); update("BYPASS OFF");}}
private void toggleSpeed(){ speed=!speed; if(speed&&pid!=-1){ mem.writeFloat(OM,1.8f); mem.writeFloat(OSprint,2.2f); mem.writeFloat(OJ,1.4f); sps.setText("ON"); sps.setTextColor(Color.argb(255,0,255,136)); update("SPEED ON");}else{ if(pid!=-1){ mem.writeFloat(OM,1f); mem.writeFloat(OSprint,1f); mem.writeFloat(OJ,1f);} sps.setText("OFF"); sps.setTextColor(Color.argb(255,255,80,80)); update("SPEED OFF");} circle.invalidate();}
private void toggleRadar(){ radar=!radar; if(radar){ rs.setText("ON"); rs.setTextColor(Color.argb(255,0,255,136)); update("RADAR ON");}else{ rs.setText("OFF"); rs.setTextColor(Color.argb(255,255,80,80)); update("RADAR OFF");}}
private void update(String msg){ h.post(()->{ String base=stats.getText().toString(); String[] parts=base.split("\\|"); if(parts.length>=4)stats.setText(parts[0].trim()+" | "+parts[1].trim()+" | "+parts[2].trim()+" | "+parts[3].trim()+" | "+msg); else stats.setText(base+" | "+msg);});}
private final Runnable radarUp=()->{ if(radar&&pid!=-1){ View rv=overlay.getChildAt(overlay.indexOfChild(stats)+6); if(rv!=null)rv.invalidate();} h.postDelayed(radarUp,200);};
private void startFps(){ last=System.nanoTime(); cb=new Choreographer.FrameCallback(){ public void doFrame(long t){ fpsCount++; long now=System.nanoTime(); if(now-last>=1000000000L){ fps=(int)(fpsCount*1000000000L/(now-last)); fpsCount=0; last=now;} Choreographer.getInstance().postFrameCallback(this);}}; Choreographer.getInstance().postFrameCallback(cb);}
private final Runnable statsUp=new Runnable(){ public void run(){ int cpu=getCpu(), ram=getRam(), bat=getBat(); String extra=""; if(tuning)extra+=" T:ON"; if(spob)extra+=" S:ON"; if(bypass)extra+=" B:ON"; if(speed)extra+=" SPD:ON"; if(radar)extra+=" R:ON"; if(extra.isEmpty())extra=" idle"; String s=String.format("CPU %2d%% | RAM %2d%% | FPS %2d | BAT %2d%%%s",cpu,ram,fps,bat,extra); stats.setText(s); stats.setTextColor((cpu>85||ram>88)?Color.argb(255,255,68,102):(cpu>65||ram>72)?Color.argb(255,255,170,0):Color.argb(230,220,220,235)); h.postDelayed(this,1000);}};
private int getCpu(){ try{RandomAccessFile f=new RandomAccessFile("/proc/stat","r"); String l=f.readLine(); f.close(); String[] t=l.trim().split("\\s+"); long idle=Long.parseLong(t[4]); long total=0; for(int i=1;i<Math.min(t.length,9);i++)total+=Long.parseLong(t[i]); if(prev!=null){ long dIdle=idle-prev[0], dTotal=total-prev[1]; prev=new long[]{idle,total}; return(int)(100L*(dTotal-dIdle)/Math.max(dTotal,1));} prev=new long[]{idle,total}; return 0;}catch(Exception e){return 0;}}
private int getRam(){ ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE); ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo(); am.getMemoryInfo(mi); if(mi.totalMem==0)return 0; return(int)(100L-mi.availMem*100L/mi.totalMem);}
private int getBat(){ Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED)); if(i==null)return 0; int l=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1), s=i.getIntExtra(BatteryManager.EXTRA_SCALE,-1); if(l<0||s<=0)return 0; return(int)(l*100f/s);}
private class Resize implements View.OnTouchListener{ float sx; int sw; public boolean onTouch(View v,MotionEvent e){ if(e.getAction()==MotionEvent.ACTION_DOWN){ sx=e.getRawX(); sw=op.width; return true;} if(e.getAction()==MotionEvent.ACTION_MOVE){ int nw=Math.max(380,Math.min(720,(int)(sw+sx-e.getRawX()))); op.width=nw; wm.updateViewLayout(overlay,op); return true;} return false;}}
private static class Drag implements View.OnTouchListener{ WindowManager w; WindowManager.LayoutParams p; View v; int ix,iy; float itx,ity; Drag(WindowManager w,WindowManager.LayoutParams p,View v){ this.w=w; this.p=p; this.v=v;} public boolean onTouch(View view,MotionEvent e){ if(e.getAction()==MotionEvent.ACTION_DOWN){ ix=p.x; iy=p.y; itx=e.getRawX(); ity=e.getRawY(); return true;} if(e.getAction()==MotionEvent.ACTION_MOVE){ p.x=ix+(int)(e.getRawX()-itx); p.y=iy+(int)(e.getRawY()-ity); w.updateViewLayout(v,p); return true;} return false;}}
@Override public void onDestroy(){ super.onDestroy(); h.removeCallbacksAndMessages(null); if(cb!=null)Choreographer.getInstance().removeFrameCallback(cb); if(overlay!=null)wm.removeView(overlay); if(circle!=null&&circle.getParent()!=null)wm.removeView(circle); mem.detach();}
@Override public IBinder onBind(Intent i){return null;}
private void createChannel(){ if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){ NotificationChannel ch=new NotificationChannel(CID,"dBost",NotificationManager.IMPORTANCE_LOW); getSystemService(NotificationManager.class).createNotificationChannel(ch);}}
private static class MemoryBridge{ int pid; boolean attached; static{ try{System.loadLibrary("mem_bridge");}catch(UnsatisfiedLinkError e){}} public native boolean nativeAttach(int pid); public native float nativeReadFloat(long addr); public native void nativeWriteFloat(long addr,float val); public native int nativeReadInt(long addr); public native void nativeWriteInt(long addr,int val); public int findPid(){ try{Process p=Runtime.getRuntime().exec("ps -A"); BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream())); String l; while((l=r.readLine())!=null){ if(l.contains("com.dts.freefireth"))return Integer.parseInt(l.trim().split("\\s+")[1]);}}catch(Exception e){} return -1;} public boolean attach(int p){ pid=p; try{attached=nativeAttach(p);}catch(UnsatisfiedLinkError e){attached=false;} return attached;} public void detach(){attached=false;} public float readFloat(long a){ if(!attached)return 0; try{return nativeReadFloat(a);}catch(Exception e){return 0;}} public void writeFloat(long a,float v){ if(!attached)return; try{nativeWriteFloat(a,v);}catch(Exception e){}} public int readInt(long a){ if(!attached)return 0; try{return nativeReadInt(a);}catch(Exception e){return 0;}} public void writeInt(long a,int v){ if(!attached)return; try{nativeWriteInt(a,v);}catch(Exception e){}}}}